# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloomberg.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bloomberg.proto',
  package='org.jok.util.bloomberg.data',
  serialized_pb='\n\x0f\x62loomberg.proto\x12\x1borg.jok.util.bloomberg.data\"x\n\x0c\x42loombergRow\x12\x0e\n\x06ticker\x18\x01 \x02(\t\x12\r\n\x05\x66ield\x18\x02 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\x03\x12\x13\n\x0bvalueDouble\x18\x04 \x01(\x01\x12\x13\n\x0bvalueString\x18\x06 \x01(\t\x12\x11\n\terrorCode\x18\x07 \x01(\x05\"]\n\x11\x42loombergResponse\x12\x0f\n\x07request\x18\x01 \x02(\t\x12\x37\n\x04rows\x18\x02 \x03(\x0b\x32).org.jok.util.bloomberg.data.BloombergRow\"\xf8\x01\n\x10\x42loombergRequest\x12\x0f\n\x07rawmode\x18\x01 \x02(\x08\x12\x11\n\tstartdate\x18\x02 \x01(\x03\x12\x0f\n\x07\x65nddate\x18\x06 \x01(\x03\x12\x0f\n\x07tickers\x18\x03 \x03(\t\x12\x0e\n\x06\x66ields\x18\x04 \x03(\t\x12\x12\n\ncurrencies\x18\x07 \x03(\t\x12\x11\n\tfrequency\x18\x08 \x01(\t\x12\x12\n\nrawcontent\x18\x05 \x01(\t\x12\x0f\n\x07program\x18\t \x01(\t\x12\x1c\n\x14responsebuilderclass\x18\n \x01(\t\x12\x12\n\ntickertype\x18\x0b \x01(\t\x12\x10\n\x08terminal\x18\x0c \x01(\x08\"E\n\x19\x42loombergTickerDictionary\x12\x17\n\x0f\x62loombergticker\x18\x01 \x02(\t\x12\x0f\n\x07\x61liases\x18\x02 \x03(\t\"\xa5\x01\n\x13\x42loombergDictionary\x12?\n\x0ftickeroperation\x18\x01 \x02(\x0e\x32&.org.jok.util.bloomberg.data.Operation\x12M\n\rtickerentries\x18\x02 \x03(\x0b\x32\x36.org.jok.util.bloomberg.data.BloombergTickerDictionary*8\n\tOperation\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\t\n\x05\x43LEAR\x10\x02\x12\x08\n\x04NONE\x10\x03')

_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='org.jok.util.bloomberg.data.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEAR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=755,
  serialized_end=811,
)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
CREATE = 0
UPDATE = 1
CLEAR = 2
NONE = 3



_BLOOMBERGROW = _descriptor.Descriptor(
  name='BloombergRow',
  full_name='org.jok.util.bloomberg.data.BloombergRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='org.jok.util.bloomberg.data.BloombergRow.ticker', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field', full_name='org.jok.util.bloomberg.data.BloombergRow.field', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='org.jok.util.bloomberg.data.BloombergRow.date', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valueDouble', full_name='org.jok.util.bloomberg.data.BloombergRow.valueDouble', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valueString', full_name='org.jok.util.bloomberg.data.BloombergRow.valueString', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='org.jok.util.bloomberg.data.BloombergRow.errorCode', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=168,
)


_BLOOMBERGRESPONSE = _descriptor.Descriptor(
  name='BloombergResponse',
  full_name='org.jok.util.bloomberg.data.BloombergResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='org.jok.util.bloomberg.data.BloombergResponse.request', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='org.jok.util.bloomberg.data.BloombergResponse.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=170,
  serialized_end=263,
)


_BLOOMBERGREQUEST = _descriptor.Descriptor(
  name='BloombergRequest',
  full_name='org.jok.util.bloomberg.data.BloombergRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rawmode', full_name='org.jok.util.bloomberg.data.BloombergRequest.rawmode', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startdate', full_name='org.jok.util.bloomberg.data.BloombergRequest.startdate', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enddate', full_name='org.jok.util.bloomberg.data.BloombergRequest.enddate', index=2,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tickers', full_name='org.jok.util.bloomberg.data.BloombergRequest.tickers', index=3,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='org.jok.util.bloomberg.data.BloombergRequest.fields', index=4,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currencies', full_name='org.jok.util.bloomberg.data.BloombergRequest.currencies', index=5,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='org.jok.util.bloomberg.data.BloombergRequest.frequency', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rawcontent', full_name='org.jok.util.bloomberg.data.BloombergRequest.rawcontent', index=7,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='program', full_name='org.jok.util.bloomberg.data.BloombergRequest.program', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responsebuilderclass', full_name='org.jok.util.bloomberg.data.BloombergRequest.responsebuilderclass', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tickertype', full_name='org.jok.util.bloomberg.data.BloombergRequest.tickertype', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='terminal', full_name='org.jok.util.bloomberg.data.BloombergRequest.terminal', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=266,
  serialized_end=514,
)


_BLOOMBERGTICKERDICTIONARY = _descriptor.Descriptor(
  name='BloombergTickerDictionary',
  full_name='org.jok.util.bloomberg.data.BloombergTickerDictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bloombergticker', full_name='org.jok.util.bloomberg.data.BloombergTickerDictionary.bloombergticker', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aliases', full_name='org.jok.util.bloomberg.data.BloombergTickerDictionary.aliases', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=516,
  serialized_end=585,
)


_BLOOMBERGDICTIONARY = _descriptor.Descriptor(
  name='BloombergDictionary',
  full_name='org.jok.util.bloomberg.data.BloombergDictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tickeroperation', full_name='org.jok.util.bloomberg.data.BloombergDictionary.tickeroperation', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tickerentries', full_name='org.jok.util.bloomberg.data.BloombergDictionary.tickerentries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=588,
  serialized_end=753,
)

_BLOOMBERGRESPONSE.fields_by_name['rows'].message_type = _BLOOMBERGROW
_BLOOMBERGDICTIONARY.fields_by_name['tickeroperation'].enum_type = _OPERATION
_BLOOMBERGDICTIONARY.fields_by_name['tickerentries'].message_type = _BLOOMBERGTICKERDICTIONARY
DESCRIPTOR.message_types_by_name['BloombergRow'] = _BLOOMBERGROW
DESCRIPTOR.message_types_by_name['BloombergResponse'] = _BLOOMBERGRESPONSE
DESCRIPTOR.message_types_by_name['BloombergRequest'] = _BLOOMBERGREQUEST
DESCRIPTOR.message_types_by_name['BloombergTickerDictionary'] = _BLOOMBERGTICKERDICTIONARY
DESCRIPTOR.message_types_by_name['BloombergDictionary'] = _BLOOMBERGDICTIONARY

class BloombergRow(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOOMBERGROW

  # @@protoc_insertion_point(class_scope:org.jok.util.bloomberg.data.BloombergRow)

class BloombergResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOOMBERGRESPONSE

  # @@protoc_insertion_point(class_scope:org.jok.util.bloomberg.data.BloombergResponse)

class BloombergRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOOMBERGREQUEST

  # @@protoc_insertion_point(class_scope:org.jok.util.bloomberg.data.BloombergRequest)

class BloombergTickerDictionary(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOOMBERGTICKERDICTIONARY

  # @@protoc_insertion_point(class_scope:org.jok.util.bloomberg.data.BloombergTickerDictionary)

class BloombergDictionary(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOOMBERGDICTIONARY

  # @@protoc_insertion_point(class_scope:org.jok.util.bloomberg.data.BloombergDictionary)


# @@protoc_insertion_point(module_scope)
